In [1]:
num = int(input("enter an integer"))
print(type(num))

enter an integer5
<class 'int'>


In [2]:
for i in range(1,11):
  print(f'{num} x {i} = {num*i}')

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [4]:
a= float(input("enter first number:"))
b= float(input("enter second number:"))
print(f'The sum of{a} and {b} is {a+b}')
print(f'substraction:{a-b}')
print(f'Multiplication:{a*b}')
print(f'Division:{a/b}')
print(f'Remainder:{a%b}')


enter first number:8
enter second number:5
The sum of8.0 and 5.0 is 13.0
substraction:3.0
Multiplication:40.0
Division:1.6
Remainder:3.0


In [5]:
nums=[12,14,19,10,20]
tot=0
for x in nums:
  tot = tot + x
  print(f'The total is {tot}')
avg = tot/len(nums)
print(f'The average is {avg}')

The total is 12
The total is 26
The total is 45
The total is 55
The total is 75
The average is 15.0


In [6]:
import numpy as np

In [7]:
a1d = np.array([72.5,81,54,90])
print("Array:", a1d)
print("Type:",type(a1d))

Array: [72.5 81.  54.  90. ]
Type: <class 'numpy.ndarray'>


In [9]:
a0d=np.array(46)
print(f'Array:{a0d}')
print(f'Type:Type{a0d.dtype}')

Array:46
Type:Typeint64


In [10]:
a2d=np.array([[1,2,3],[4,5,6]])
print(f'Array:{a2d}')
print(f'type:{a2d.dtype}')
print(f'ndim:{a2d.ndim}')
print(f'shape:{a2d.shape}')
print(f'size:{a2d.size}')


Array:[[1 2 3]
 [4 5 6]]
type:int64
ndim:2
shape:(2, 3)
size:6


create 3d array with shape 2,3,3 check iy by printinting dimension and shape

In [12]:
a3d=np.array([[1,2,3],[4,5,6],[14,15,16]])
print(f'Array:{a3d}')
print(f'type:{a3d.dtype}')
print(f'ndim:{a3d.ndim}')
print(f'shape:{a3d.shape}')
print(f'size:{a3d.size}')

Array:[[ 1  2  3]
 [ 4  5  6]
 [14 15 16]]
type:int64
ndim:2
shape:(3, 3)
size:9


In [13]:
print(a1d[2])

54.0


In [14]:
print(a3d[0,1])

2


In [15]:
print(a1d[1:4])

[81. 54. 90.]


In [16]:
print(a2d[:, 1])

[2 5]


In [17]:
print(a3d[::-1])

[[14 15 16]
 [ 4  5  6]
 [ 1  2  3]]


In [18]:
print(a1d[::-1])

[90.  54.  81.  72.5]


In [19]:
a1d[1]=22
print(a1d)

[72.5 22.  54.  90. ]


write a program to take 12 elements in an array and reverse only the first 6 values

In [20]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr[:6] = arr[:6][::-1]

print("Modified array:", arr)


Modified array: [ 6  5  4  3  2  1  7  8  9 10 11 12]


In [22]:
a3d=np.array([[[1,2,3],[4,5,6],[4,5,6]],[[4,5,6],[14,15,16],[17,18,19]]])
print(f'Array:{a3d}')
print(f'type:{a3d.dtype}')
print(f'ndim:{a3d.ndim}')
print(f'shape:{a3d.shape}')
print(f'size:{a3d.size}')

Array:[[[ 1  2  3]
  [ 4  5  6]
  [ 4  5  6]]

 [[ 4  5  6]
  [14 15 16]
  [17 18 19]]]
type:int64
ndim:3
shape:(2, 3, 3)
size:18


In [24]:
print(f'Array:{a2d}')
print(f'row1,col2:{a2d[0,1]}')
print(f'row2,col3:{a2d[1,2]}')
print(f'row3,col1:{a2d[1,0]}')
print(f'Second row:{a2d[1,:]}')
print(f'Second row:{a2d[1]}')
print(f'Second column:{a2d[:,1]}')
print(f'Third column:{a2d[:,1]}')

Array:[[1 2 3]
 [4 5 6]]
row1,col2:2
row2,col3:6
row3,col1:4
Second row:[4 5 6]
Second row:[4 5 6]
Second column:[2 5]
Third column:[2 5]


In [25]:
print(f'Array{a1d}')

Array[72.5 22.  54.  90. ]


In [28]:
print(f'First four elements:{a1d[:4]}')
print(f'First three elements:{a1d[:3]}')
print(f'First three elements:{a1d[:3]}')

First four elements:[72.5 22.  54.  90. ]
First three elements:[72.5 22.  54. ]
First three elements:[72.5 22.  54. ]


In [30]:
print(a1d)

[72.5 22.  54.  90. ]


In [33]:
print(np.max(a1d))

90.0


In [35]:
print(f'Array:{a3d}')
print(f'row1, col2:{a3d[0,0,1]}')
print(f'row2, col3:{a3d[1,1,2]}')

Array:[[[ 1  2  3]
  [ 4  5  6]
  [ 4  5  6]]

 [[ 4  5  6]
  [14 15 16]
  [17 18 19]]]
row1, col2:2
row2, col3:16


In [36]:
a=[1,2,3,4,5,6,7,8,9,10,11,12]
a[:6]=a[5::-1]
print(a)

[6, 5, 4, 3, 2, 1, 7, 8, 9, 10, 11, 12]


create an array from scratch

In [39]:
ze =np.zeros(5)
print(ze)
print(f'Type:{ze.dtype}')
print(f'ndim:{ze.ndim}')
print(f'shape:{ze.shape}')
print(f'size:{ze.size}')

[0. 0. 0. 0. 0.]
Type:float64
ndim:1
shape:(5,)
size:5


In [40]:
one =np.ones(5)
print(one)
print(f'Type:{one.dtype}')
print(f'ndim:{one.ndim}')
print(f'shape:{one.shape}')
print(f'size:{one.size}')

[1. 1. 1. 1. 1.]
Type:float64
ndim:1
shape:(5,)
size:5


In [43]:
one =np.ones((2,3), dtype=int)
print(one)
print(f'Type:{one.dtype}')
print(f'ndim:{one.ndim}')
print(f'shape:{one.shape}')
print(f'size:{one.size}')

[[1 1 1]
 [1 1 1]]
Type:int64
ndim:2
shape:(2, 3)
size:6


create a 4x2 matrix filled with 100

In [45]:

matrix = np.full((4, 2), 100)

print(matrix)


[[100 100]
 [100 100]
 [100 100]
 [100 100]]


In [47]:
full=np.full((2,3),7)
print(full)
print(f'Type:{full.dtype}')
print(f'ndim:{full.ndim}')
print(f'shape:{full.shape}')
print(f'size:{full.size}')


[[7 7 7]
 [7 7 7]]
Type:int64
ndim:2
shape:(2, 3)
size:6


generating sequence with arrange() andlinspace()

In [53]:
a= np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [54]:
b= np.linspace(0,10,6)

In [55]:
print(b)

[ 0.  2.  4.  6.  8. 10.]


In [56]:
c= np.linspace(0,1,6)

In [57]:
print(c)

[0.  0.2 0.4 0.6 0.8 1. ]


#random number generation

In [58]:
np.random.seed(42)
print(f'Random decimal:{np.random.random(5)}')

Random decimal:[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [60]:
np.random.seed(42)
print(f'Random decimal:{np.random.random(8)}')

Random decimal:[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615]


In [62]:
np.random.seed(5)
print(f'Random decimal:{np.random.random(5)}')

Random decimal:[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119]


In [63]:
print(f'Random decimal:{np.random.randint(1,11, size=5)}')

Random decimal:[8 1 1 8 2]


In [64]:
print(f'Random decimal:{np.random.randint(0,1, size=5)}')

Random decimal:[0 0 0 0 0]


In [65]:
print(f'Random decimal:{np.random.randint(1,11, size=(3,3))}')

Random decimal:[[ 6  8  1]
 [ 2  5  7]
 [ 3 10 10]]


In [67]:
print(f'{np.random.rand(2,3 )}')

[[0.83349274 0.89241102 0.9580135 ]
 [0.56133712 0.0905487  0.99598891]]
